### ISSUE TITLE
Extremely slow and "never-end" installation

### ISSUE THREAD

**Issue by thevenmuthu** [dwavesystems/dwave-ocean-sdk#119]
**Description**
Hi. I find the library installation is very slow and never end, so far the installation on my side did not reach any completion. I am quite sure it is not due to my network. 

Can someone help validate about this issue? Thanks.

**To Reproduce**
1. virtualenv env
2. .\Scripts\activate
3. pip install dwave-ocean-sdk

**Expected behavior**
Installation will stuck for longer time. As per my observation, the installation never complete even after more than 8 hours.

**Environment:**
 - OS: Windows 10
 - Python version: 3.7.2

**Additional context**
I am using "cmder" as an alternative to plain windows command line (cmd.exe) GUI.

**Comment by arcondello** [comment]
Would it be possible to get the output of everything after the `pip install` command until it hangs?

**Comment by thevenmuthu** [comment]
Hi. Following is the console output since `pip install` command. Take note that I did halt the installation a few times before, with the assumption to run again after sometime. Output below is after 7 hours of installation run.

(env) λ pip install dwave-ocean-sdk
Collecting dwave-ocean-sdk
  Using cached dwave_ocean_sdk-3.3.0-py3-none-any.whl (7.2 kB)
Collecting dwave-hybrid==0.6.1
  Using cached dwave_hybrid-0.6.1-py3-none-any.whl (63 kB)
Collecting dwave-networkx==0.8.8
  Using cached dwave_networkx-0.8.8-py2.py3-none-any.whl (81 kB)
Collecting minorminer==0.2.5
  Using cached minorminer-0.2.5-cp37-cp37m-win32.whl (557 kB)
Collecting dwave-qbsolv==0.3.2
  Using cached dwave_qbsolv-0.3.2-cp37-cp37m-win32.whl (50 kB)
Collecting dwave-cloud-client==0.8.4
  Using cached dwave_cloud_client-0.8.4-py3-none-any.whl (87 kB)
Collecting dimod==0.9.13
  Using cached dimod-0.9.13-cp37-cp37m-win32.whl (2.2 MB)
Collecting dwave-neal==0.5.7
  Using cached dwave_neal-0.5.7-cp37-cp37m-win32.whl (73 kB)
Collecting penaltymodel-cache==0.4.3
  Using cached penaltymodel_cache-0.4.3-py3-none-any.whl (12 kB)
Collecting dwave-tabu==0.3.1
  Using cached dwave_tabu-0.3.1-cp37-cp37m-win32.whl (105 kB)
Collecting penaltymodel==0.16.4
  Using cached penaltymodel-0.16.4-py3-none-any.whl (13 kB)
Collecting dwavebinarycsp==0.1.2
  Using cached dwavebinarycsp-0.1.2-py3-none-any.whl (35 kB)
Collecting penaltymodel-lp==0.1.4
  Using cached penaltymodel_lp-0.1.4-py3-none-any.whl (7.3 kB)
Collecting penaltymodel-mip==0.2.4
  Using cached penaltymodel_mip-0.2.4-py3-none-any.whl (7.7 kB)
Collecting dwave-greedy==0.1.2
  Using cached dwave_greedy-0.1.2-cp37-cp37m-win32.whl (74 kB)
Collecting dwave-system==1.4.0
  Using cached dwave_system-1.4.0-py3-none-any.whl (82 kB)
Collecting dwave-inspector==0.2.5
  Using cached dwave_inspector-0.2.5-py3-none-any.whl (25 kB)
Collecting pyqubo==1.0.10
  Using cached pyqubo-1.0.10.tar.gz (16 kB)
Collecting numpy<2.0.0,>=1.17.3
  Using cached numpy-1.20.1-cp37-cp37m-win32.whl (11.3 MB)
Collecting plucky>=0.4.3
  Using cached plucky-0.4.3-py2.py3-none-any.whl (10 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting click>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting homebase>=1.0
  Using cached homebase-1.0.1-py2.py3-none-any.whl (11 kB)
Collecting requests[socks]>=2.18
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting networkx
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting Flask>=1.1.1
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting importlib-resources>=3.2.0
  Using cached importlib_resources-5.1.2-py3-none-any.whl (25 kB)
Collecting decorator<5.0.0,>=4.1.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting six<2.0.0,>=1.11.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting fasteners
  Using cached fasteners-0.16-py2.py3-none-any.whl (28 kB)
Collecting scipy
  Using cached scipy-1.6.1-cp37-cp37m-win32.whl (29.4 MB)
INFO: pip is looking at multiple versions of penaltymodel-lp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of penaltymodel-cache to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of penaltymodel to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of minorminer to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwavebinarycsp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-tabu to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-system to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-qbsolv to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-networkx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-neal to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-inspector to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-hybrid to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-greedy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-cloud-client to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dimod to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-ocean-sdk to determine which version is compatible with other requirements. This could take a while.
Collecting dwave-ocean-sdk
  Using cached dwave_ocean_sdk-3.2.0-py3-none-any.whl (7.3 kB)
  Using cached dwave_ocean_sdk-3.1.1-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-3.1.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-3.0.1-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-3.0.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.6.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.5.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.4.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.3.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.2.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.1.1-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.1.0-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.0.1-py3-none-any.whl (6.9 kB)
  Using cached dwave_ocean_sdk-2.0.0-py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.6.0-py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.5.0-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.4.0-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.3.0-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.2.0-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.1.0-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.0.4-py2.py3-none-any.whl (6.8 kB)
  Using cached dwave_ocean_sdk-1.0.3-py2.py3-none-any.whl (6.5 kB)
  Using cached dwave-ocean-sdk-1.0.2.tar.gz (2.1 kB)
  Using cached dwave_ocean_sdk-1.0.1-py2.py3-none-any.whl (2.2 kB)
  Using cached dwave_ocean_sdk-1.0.0-py3-none-any.whl (1.7 kB)
  Using cached dwave_ocean_sdk-0.3.1-py3-none-any.whl (1.7 kB)
  Using cached dwave_ocean_sdk-0.3.0-py3-none-any.whl (1.7 kB)
Collecting dwave-cloud-client==0.8.2
  Using cached dwave_cloud_client-0.8.2-py3-none-any.whl (85 kB)
Collecting dwave-inspector==0.2.4
  Using cached dwave_inspector-0.2.4-py3-none-any.whl (24 kB)
Collecting dwave-system==1.3.0
  Using cached dwave_system-1.3.0-py3-none-any.whl (82 kB)
Collecting pyqubo==1.0.7
  Using cached pyqubo-1.0.7.tar.gz (19 kB)
Collecting dwave-neal==0.5.6
  Using cached dwave_neal-0.5.6-cp37-cp37m-win32.whl (76 kB)
Collecting penaltymodel-cache==0.4.1
  Using cached penaltymodel_cache-0.4.1-py3-none-any.whl (11 kB)
Collecting dwave-greedy==0.1.1
  Using cached dwave_greedy-0.1.1-cp37-cp37m-win32.whl (75 kB)
Collecting penaltymodel-mip==0.2.3
  Using cached penaltymodel_mip-0.2.3-py3-none-any.whl (7.7 kB)
Collecting dwave-hybrid==0.6.0
  Using cached dwave_hybrid-0.6.0-py3-none-any.whl (93 kB)
Collecting minorminer==0.2.3
  Using cached minorminer-0.2.3-cp37-cp37m-win32.whl (548 kB)
Collecting penaltymodel-lp==0.1.3
  Using cached penaltymodel_lp-0.1.3-py3-none-any.whl (7.3 kB)
Collecting dwave-tabu==0.3.0
  Using cached dwave_tabu-0.3.0-cp37-cp37m-win32.whl (91 kB)
Collecting dimod==0.9.10
  Using cached dimod-0.9.10-cp37-cp37m-win32.whl (2.0 MB)
Collecting penaltymodel==0.16.3
  Using cached penaltymodel-0.16.3-py3-none-any.whl (13 kB)
Collecting dwave-cloud-client==0.8.1
  Using cached dwave_cloud_client-0.8.1-py3-none-any.whl (85 kB)
Collecting dwave-qbsolv==0.3.1
  Using cached dwave_qbsolv-0.3.1-cp37-cp37m-win32.whl (50 kB)
Collecting pyqubo==0.4.0
  Using cached pyqubo-0.4.0.tar.gz (33 kB)
Collecting dwave-system==1.2.1
  Using cached dwave_system-1.2.1-py3-none-any.whl (98 kB)
Collecting dimod==0.9.9
  Using cached dimod-0.9.9-cp37-cp37m-win32.whl (2.0 MB)
Collecting dimod==0.9.7
  Using cached dimod-0.9.7-cp37-cp37m-win32.whl (2.0 MB)
Collecting dwave-system==1.1.1
  Using cached dwave_system-1.1.1-py3-none-any.whl (97 kB)
Collecting dwave-hybrid==0.5.1
  Using cached dwave_hybrid-0.5.1-py3-none-any.whl (91 kB)
Collecting dwave-networkx==0.8.7
  Using cached dwave_networkx-0.8.7-py2.py3-none-any.whl (81 kB)
Collecting dwave-cloud-client==0.7.7
  Using cached dwave_cloud_client-0.7.7-py3-none-any.whl (85 kB)
Collecting dimod==0.9.5
  Using cached dimod-0.9.5-cp37-cp37m-win32.whl (1.6 MB)
Collecting minorminer==0.2.0
  Using cached minorminer-0.2.0-cp37-cp37m-win32.whl (425 kB)
Collecting dwave-qbsolv==0.3.0
  Using cached dwave_qbsolv-0.3.0-cp37-cp37m-win32.whl (50 kB)
Collecting dwave-system==0.9.9
  Using cached dwave_system-0.9.9-py3-none-any.whl (91 kB)
Collecting dwave-neal==0.5.4
  Using cached dwave_neal-0.5.4-cp37-cp37m-win32.whl (72 kB)
Collecting dwave-inspector==0.2.3
  Using cached dwave_inspector-0.2.3-py3-none-any.whl (24 kB)
Collecting dwave-cloud-client==0.7.5
  Using cached dwave_cloud_client-0.7.5-py2.py3-none-any.whl (84 kB)
Collecting dwave-inspector==0.2.2
  Using cached dwave_inspector-0.2.2-py3-none-any.whl (24 kB)
Collecting dwave-networkx==0.8.6
  Using cached dwave_networkx-0.8.6-py2.py3-none-any.whl (81 kB)
INFO: pip is looking at multiple versions of penaltymodel-lp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of penaltymodel-cache to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of penaltymodel to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of minorminer to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwavebinarycsp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-tabu to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-system to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-qbsolv to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-networkx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-neal to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-inspector to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-hybrid to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-cloud-client to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dimod to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwave-ocean-sdk to determine which version is compatible with other requirements. This could take a while.
Collecting dwave-hybrid==0.5.0
  Using cached dwave_hybrid-0.5.0-py3-none-any.whl (90 kB)
Collecting minorminer==0.1.9
  Using cached minorminer-0.1.9-cp37-cp37m-win32.whl (247 kB)
Collecting dwave-system==0.9.6
  Using cached dwave_system-0.9.6-py3-none-any.whl (87 kB)
Collecting dwave-cloud-client==0.7.4
  Using cached dwave_cloud_client-0.7.4-py2.py3-none-any.whl (83 kB)
Collecting dimod==0.9.4
  Using cached dimod-0.9.4-cp37-cp37m-win32.whl (1.6 MB)
Collecting dwave-cloud-client==0.7.3
  Using cached dwave_cloud_client-0.7.3-py2.py3-none-any.whl (83 kB)
Collecting dimod==0.9.3
  Using cached dimod-0.9.3-cp37-cp37m-win32.whl (1.6 MB)
Collecting dwave-inspector==0.2.1
  Using cached dwave_inspector-0.2.1-py2.py3-none-any.whl (24 kB)
Collecting dwave-hybrid==0.4.3
  Using cached dwave_hybrid-0.4.3-py2.py3-none-any.whl (90 kB)
Collecting dimod==0.9.2
  Using cached dimod-0.9.2-cp37-cp37m-win32.whl (1.6 MB)
Collecting dwave-cloud-client==0.7.2
  Using cached dwave_cloud_client-0.7.2-py2.py3-none-any.whl (83 kB)
Collecting dwave-system==0.9.5
  Using cached dwave_system-0.9.5-py3-none-any.whl (87 kB)
Collecting dwave-inspector==0.1.5
  Using cached dwave_inspector-0.1.5-py2.py3-none-any.whl (24 kB)
Collecting dwave-system==0.9.4
  Using cached dwave_system-0.9.4-py3-none-any.whl (86 kB)
Collecting dwave-tabu==0.2.2
  Using cached dwave_tabu-0.2.2-cp37-cp37m-win32.whl (91 kB)
Collecting dimod==0.9.1
  Using cached dimod-0.9.1-cp37-cp37m-win32.whl (1.6 MB)
Collecting dwave-cloud-client==0.7.1
  Using cached dwave_cloud_client-0.7.1-py2.py3-none-any.whl (83 kB)
Collecting penaltymodel-mip==0.2.2
  Using cached penaltymodel_mip-0.2.2-py2.py3-none-any.whl (7.7 kB)
Collecting dwavebinarycsp==0.1.1
  Using cached dwavebinarycsp-0.1.1-py3-none-any.whl (35 kB)
Collecting dwave-system==0.9.2
  Using cached dwave_system-0.9.2-py3-none-any.whl (86 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
Collecting dwave-networkx==0.8.4
  Using cached dwave_networkx-0.8.4-py2.py3-none-any.whl (81 kB)
Collecting dwave-system==0.9.1
  Using cached dwave_system-0.9.1-py3-none-any.whl (86 kB)
Collecting dwave-hybrid==0.4.2
  Using cached dwave_hybrid-0.4.2-py2.py3-none-any.whl (90 kB)
Collecting dwave-inspector==0.1.3
  Using cached dwave_inspector-0.1.3-py2.py3-none-any.whl (25 kB)
Collecting dwave-cloud-client==0.7.0
  Using cached dwave_cloud_client-0.7.0-py2.py3-none-any.whl (82 kB)
Collecting dimod==0.9.0
  Using cached dimod-0.9.0-cp37-cp37m-win32.whl (1.6 MB)
Collecting dwave-neal==0.5.3
  Using cached dwave_neal-0.5.3-cp37-cp37m-win32.whl (72 kB)
Collecting dwavebinarycsp==0.1.0
  Using cached dwavebinarycsp-0.1.0-py3-none-any.whl (36 kB)
Collecting dwave-qbsolv==0.2.10
  Using cached dwave_qbsolv-0.2.10-cp37-cp37m-win32.whl (50 kB)
Collecting dwave-cloud-client==0.6.3
  Using cached dwave_cloud_client-0.6.3-py2.py3-none-any.whl (79 kB)
Collecting penaltymodel-cache==0.4.0
  Using cached penaltymodel_cache-0.4.0-py2.py3-none-any.whl (10 kB)
Collecting dimod==0.8.21
  Using cached dimod-0.8.21-cp37-cp37m-win32.whl (253 kB)
Collecting dwave-system==0.8.1
  Using cached dwave_system-0.8.1-py2.py3-none-any.whl (81 kB)
Collecting dwave-networkx==0.8.3
  Using cached dwave_networkx-0.8.3-py2.py3-none-any.whl (79 kB)
Collecting penaltymodel==0.16.2
  Using cached penaltymodel-0.16.2-py2.py3-none-any.whl (12 kB)
Collecting dwavebinarycsp==0.0.12
  Using cached dwavebinarycsp-0.0.12-py2.py3-none-any.whl (36 kB)
Collecting numpy<1.16.0
  Using cached numpy-1.15.4-cp37-none-win32.whl (9.9 MB)
Collecting dwave-neal<0.6.0,>=0.5.0
  Using cached dwave_neal-0.5.5-cp37-cp37m-win32.whl (76 kB)
Collecting penaltymodel-mip<0.3.0,>=0.2.0
  Using cached penaltymodel_mip-0.2.1-py2.py3-none-any.whl (7.1 kB)
  Using cached penaltymodel_mip-0.2.0-py2.py3-none-any.whl (7.0 kB)
Collecting penaltymodel-lp<0.2.0,>=0.1.0
  Using cached penaltymodel_lp-0.1.2-py3-none-any.whl (7.3 kB)
  Using cached penaltymodel_lp-0.1.1-py3-none-any.whl (7.3 kB)
  Using cached penaltymodel_lp-0.1.0-py3-none-any.whl (6.3 kB)
Collecting penaltymodel-cache<0.5.0,>=0.4.0
  Using cached penaltymodel_cache-0.4.2-py3-none-any.whl (12 kB)
Collecting penaltymodel<0.17.0,>=0.16.0
  Using cached penaltymodel-0.16.0-py2.py3-none-any.whl (12 kB)
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
Collecting numpy<1.16.0
  Using cached numpy-1.15.3-cp37-none-win32.whl (9.9 MB)
  Using cached numpy-1.15.2-cp37-none-win32.whl (9.9 MB)
  Using cached numpy-1.15.1-cp37-none-win32.whl (9.9 MB)
  Using cached numpy-1.15.0-cp37-none-win32.whl (9.9 MB)
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of networkx to determine which version is compatible with other requirements. This could take a while.
Collecting networkx
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
  Using cached networkx-2.3.zip (1.7 MB)
  Using cached networkx-2.2.zip (1.7 MB)
  Using cached networkx-2.1.zip (1.6 MB)
  Using cached networkx-2.0.zip (1.5 MB)
INFO: pip is looking at multiple versions of networkx to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
Collecting minorminer>=0.1.7
  Using cached minorminer-0.1.8-cp37-cp37m-win32.whl (246 kB)
  Using cached minorminer-0.1.7-cp37-cp37m-win32.whl (251 kB)
INFO: pip is looking at multiple versions of homebase to determine which version is compatible with other requirements. This could take a while.
Collecting homebase<2.0.0,>=1.0.0
  Using cached homebase-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting enum34==1.1.6
  Using cached enum34-1.1.6-py3-none-any.whl (12 kB)
INFO: pip is looking at multiple versions of enum34 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwavebinarycsp[mip] to determine which version is compatible with other requirements. This could take a while.
Collecting dwavebinarycsp[mip]<0.1.0,>=0.0.9
  Using cached dwavebinarycsp-0.0.11-py2.py3-none-any.whl (36 kB)
  Using cached dwavebinarycsp-0.0.10-py2.py3-none-any.whl (36 kB)
  Using cached dwavebinarycsp-0.0.9-py2.py3-none-any.whl (36 kB)
Collecting penaltymodel<0.16.0,>=0.15.0
  Using cached penaltymodel-0.15.4-py2.py3-none-any.whl (11 kB)
Collecting penaltymodel-cache<0.4.0,>=0.3.2
  Using cached penaltymodel_cache-0.3.3-py2.py3-none-any.whl (10 kB)
Collecting penaltymodel-mip<0.2.0,>=0.1.2
  Using cached penaltymodel_mip-0.1.4-py2.py3-none-any.whl (6.9 kB)
  Using cached penaltymodel_mip-0.1.3-py2.py3-none-any.whl (6.9 kB)
  Using cached penaltymodel_mip-0.1.2-py2.py3-none-any.whl (6.9 kB)
Collecting penaltymodel-cache<0.4.0,>=0.3.2
  Using cached penaltymodel_cache-0.3.2-py2.py3-none-any.whl (10 kB)
Collecting penaltymodel<0.16.0,>=0.15.0
  Using cached penaltymodel-0.15.3-py2.py3-none-any.whl (11 kB)
  Using cached penaltymodel-0.15.2-py2.py3-none-any.whl (11 kB)
  Using cached penaltymodel-0.15.1-py2.py3-none-any.whl (11 kB)
  Using cached penaltymodel-0.15.0-py2.py3-none-any.whl (11 kB)
Collecting dwave-tabu<0.3.0,>=0.2.0
  Using cached dwave_tabu-0.2.1-cp37-cp37m-win32.whl (91 kB)
  Using cached dwave_tabu-0.2.0-cp37-cp37m-win32.whl (91 kB)
INFO: pip is looking at multiple versions of homebase to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of enum34 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of dwavebinarycsp[mip] to determine which version is compatible with other requirements. This could take a while.
Collecting dwave-cloud-client<0.7.0,>=0.6.0
  Using cached dwave_cloud_client-0.6.2-py2.py3-none-any.whl (77 kB)
  Using cached dwave_cloud_client-0.6.1-py2.py3-none-any.whl (66 kB)
  Using cached dwave_cloud_client-0.6.0-py2.py3-none-any.whl (66 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

**Comment by thevenmuthu** [comment]
Hi @arcondello. Any update on this issue?

**Comment by arcondello** [comment]
Hi @thevenmuthu , this looks like something is going wrong with you `pip`, can you try `pip install dwave-ocean-sdk --no-cache-dir`? Also, for the sake of completeness, updating your pip?

**Comment by thevenmuthu** [comment]
Hi @arcondello. Thanks for your suggestion. It seems things worked well once I upgrade my Python from 3.7 to 3.9. I believe Pip has been upgraded in parallel with Python. Thanks again.
