### ISSUE TITLE
Doc refers to SAPI endpoints on the Leap Dashboard; these have been removed. 

### ISSUE THREAD

**Issue by fionahanington** [dwavesystems/dwave-ocean-sdk#182]
**Description**
Doc refers to SAPI endpoints on the Leap Dashboard; these have been removed. 

**To Reproduce**
Look https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html
Note paragraph stating:
"You can find all the above information when you log in to your D-Wave account. For Leap users, select the Dashboard tab; for on-premises (Qubist) users, select the Solver API tab and the API Tokens menu item under your user name."

**Comment by JoelPasvolsky** [comment]
@fionahanington, I think this issue was for the since-updated page -- please take another look at the page and let me know if you still see a problem. Thanks!
