### ISSUE TITLE
dwave.conf issue 

### ISSUE THREAD

**Issue by Hadeelmqs** [dwavesystems/dwave-ocean-sdk#283]
Hi everyone,

I'm trying to run this code
        sampler = EmbeddingComposite(DWaveSampler(solver={'topology__type__eq':'pegasus'}))
        sampleset = sampler.sample_qubo(Q,num_reads=myreads,chain_strength=mychain,annealing_time=mytime)
        rawoutput = sampleset.aggregate()

where it says 
ValueError: API token not defined

I don't have such file: ~/.config/dwave/dwave.conf

I found this file: https://github.com/dwavesystems/dwave-ocean-sdk/blob/c04a51752dfbe5e6f460752dc51617f15d620d7f/docs/docs_cli.rst#L143

but sill I don't know what I have to add to dwave.conf

**Comment by randomir** [comment]
Hi @Hadeelmqs,

The easiest way to [configure Ocean to access Leap solvers](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html#sapi-access) is by running [`dwave setup`](https://docs.ocean.dwavesys.com/en/stable/docs_cli.html#setup):
```
dwave setup --auth
```

For more details, check Ocean's [Initial Set Up](https://docs.ocean.dwavesys.com/en/stable/getting_started.html#initial-set-up) docs.
