### ISSUE TITLE
Navigation bar does not scroll to under D-Wave

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-ocean-sdk#42]
**Description**
If I open a tool deep enough to take up some serious space, the D-Wave header is at the bottom of the nav bar and I cannot scroll to its links without closing the open tool:
![image](https://user-images.githubusercontent.com/34041130/70666367-509b2780-1c23-11ea-8bec-920077e18fa1.png)

**To Reproduce**
Open any tool quite a lot

**Expected behavior**
I should be able to scroll to the links

**Environment:**
 - OS: Win
 - Python version:3.7.x

**Additional context**
Chrome browser

**Comment by JoelPasvolsky** [comment]
What do people think about moving the D-Wave section above Tools section for the unified docs? We have three links under D-Wave and will have lots of tools. Of course the Tools section is more useful, but we don't want users to not see the D-Wave section links.

**Comment by arcondello** [comment]
I think this is because you still have your cookie notice open

**Comment by JoelPasvolsky** [comment]
Nice & correct diagnosis. Thanks!
