### ISSUE TITLE
Sphinx must be version >=1.4 for sphinx.ext.githubpages

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-ocean-sdk#43]
**Description**
requirements file has just "sphinx" but sphinx.ext.githubpages is supported only from 1.4. 

**To Reproduce**
run with older version and get an error

**Expected behavior**
requirement should be sphinx>=1.4
**Environment:**
 - OS: Ubuntu 16.04.4 
 - Python version:  3.5

**Additional context**

**Comment by randomir** [comment]
Resolved with #128.
