### ISSUE TITLE
docbuild error because dwave-ocean-sdk does not require pysmt

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-ocean-sdk#44]
**Description**
the `install_requires = [` line does not include `penaltymodel_maxgap` so pysmt is not installed by default. 
Building penalty model docs produces the error:
```
WARNING: autodoc: failed to import module 'maxgap.generation' from module 'penaltymodel'; the following exception was raised:
No module named 'pysmt'
WARNING: autodoc: failed to import module 'maxgap.interface' from module 'penaltymodel'; the following exception was raised:
No module named 'pysmt'
```

**To Reproduce**
Build penaltymodel docs in an env that has dwave-ocean-sdk installed

**Expected behavior**
no build errors.

**Environment:**
 - OS: Win but unix should be the same
 - Python version: 3.6

**Additional context**
Need workaround for Win

**Comment by arcondello** [comment]
Maybe we should add an `'all'` option to https://github.com/dwavesystems/dwave-ocean-sdk/blob/bb70772095f569f4a14f23f99ea55b07cce78995/setup.py#L42
that would install all penaltymodels. It won't work on 32 bit pythons but that's probably ok for documentation purposes. I'll make the change as part of https://github.com/dwavesystems/dwave-ocean-sdk/issues/50.
