### ISSUE TITLE
Unified docs not cloning latest submodules

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-ocean-sdk#45]
**Description**
It looks to me that the submodule might link to the version at creation time, not current one; for example, dwave_networkx imports an older version and gets error:
```
WARNING: [autosummary] failed to import 'dwave_networkx.generators.chimera_elimination_order': no module named dwave_networkx.generators.chimera_elimination_order
``` 

**To Reproduce**
Open a new virtualenv, clone recursive dwave-ocean-sdk, build docs. dnx gives an error on `chimera_elimination_order` because the file docs/reference/generators.rst is not the current version 0.8.3

**Expected behavior**
Latest version of all files of submodules

**Environment:**
 - OS: Ubuntu 16
 - Python version: 3.6.5

**Additional context**
See the problem in RTD build 267998 from 2019-12-11

**Comment by arcondello** [comment]
This is an error in the specific version of dwave-networkx. If you try building the docs in dnx at https://github.com/dwavesystems/dwave_networkx/tree/0.8.3 you'll get the same warning.
