### ISSUE TITLE
Deploy version 1.6.0

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-ocean-sdk#50]
Placeholder for tracking what needs to be done before deploying version 1.6.0

- [x] merge and deploy https://github.com/dwavesystems/dwave-neal/pull/75
- [x] merge and deploy https://github.com/dwavesystems/dwave-hybrid/pull/221 --> deployed 0.4.2
- [x] merge and deploy https://github.com/dwavesystems/penaltymodel/pull/110

All of these new versions then need to be added to the sdk

**Comment by Mentors4EDU** [comment]
Do you think fixing this may fix #52, or completely unrelated?

**Comment by arcondello** [comment]
@Mentors4EDU, yes I believe so, specifically by https://github.com/dwavesystems/penaltymodel/pull/110.
