### ISSUE TITLE
Installation issue 'ERROR: Command errored out with exit status 1'

### ISSUE THREAD

**Issue by UlysseCambier** [dwavesystems/dwave-ocean-sdk#96]
**Description**
Pip dwave-ocean-sdk intallation issue.  The installation of the dwave-ocean-sdk result in an error : 'ERROR: Command errored out with exit status 1' .

**To Reproduce**
x64 architecture, Python 3.8.5 64 bits
Use the command prompt:
-C:\Users\cambi\AppData\Local\Programs\Python\Python38\python.exe -m pip install virtualenv
-ocean\Scripts\activate
-pip install dwave-ocean-sdk

**Expected behavior**
Minorminer setup finish and the dwave_ocean-sdk installation is done.

**Environment:**
 - OS: Windows 10 Family 1903 18362.959
 - Python version: 3.8.5

**Additional context**
Complete log of the error:

(ocean) C:\Users\cambi>pip install dwave-ocean-sdk
Collecting dwave-ocean-sdk
  Using cached https://files.pythonhosted.org/packages/03/7c/53ee75bbaca746f522e9d538b0aee1935a1e1db6d352b21a5526a4d4b864/dwave_ocean_sdk-2.6.0-py3-none-any.whl
Collecting dwave-system==0.9.9 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/40/3b/054be1051f30de648893db9833bf89039dbb0ec2e25df7412ab0d2b73cb5/dwave_system-0.9.9-py3-none-any.whl
Collecting dwave-inspector==0.2.3 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/ea/f8/c097cfbed7ea517ea0cffcad714ac08fba01d2845ab9b801916fca0053d2/dwave_inspector-0.2.3-py3-none-any.whl
Collecting dimod==0.9.5 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/7a/bf/c4829bddf7962f2ccb68071f6451e438a56281a4f3abb04dca27c14dfb9d/dimod-0.9.5-cp38-cp38-win_amd64.whl
Collecting dwave-neal==0.5.4 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/f6/33/2e6af01188ac9e6f3d64eefd57979a296fb8909a0cf058bffe2caa26eedb/dwave_neal-0.5.4-cp38-cp38-win_amd64.whl
Collecting dwavebinarycsp==0.1.2 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/e6/f2/8422100bfa1a9cce5c0f3ca8b088a3d1f46582c0085adb2db09837dbc0f1/dwavebinarycsp-0.1.2-py3-none-any.whl
Collecting minorminer==0.2.0 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/80/dc/f3ed9a3f58cb8a1cf64d49b0e3a8ab5006fad6d8a50bacfe46859b6f16d5/minorminer-0.2.0.tar.gz
Collecting dwave-cloud-client==0.7.7 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/42/92/b29b7570c69dce5eb67205281d954b261f7a63d6f0ffe1f37127e458ec99/dwave_cloud_client-0.7.7-py3-none-any.whl
Collecting dwave-networkx==0.8.7 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/64/3d/4d2ad7cbf7d1cd6ac3e5dae86b86b235fa41219823bc301b7929ab15f15e/dwave_networkx-0.8.7-py2.py3-none-any.whl
Collecting dwave-tabu==0.3.0 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/1c/b4/9fedd8ffb9b17e3d7953967ac832d81c635f36fa845d3a609bf563e13b04/dwave_tabu-0.3.0-cp38-cp38-win_amd64.whl
Collecting penaltymodel-lp==0.1.3 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/e2/86/4c4c4de17c7e45f1958547da6a3fe866b6a6f48bf4785575bf6cc9ab91ca/penaltymodel_lp-0.1.3-py3-none-any.whl
Collecting dwave-qbsolv==0.3.0 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/08/b7/623af2ab04ac48f79e0557b3050a9be2ae49782e2a43a73a924d36a6810d/dwave_qbsolv-0.3.0-cp38-cp38-win_amd64.whl
Collecting penaltymodel-cache==0.4.1 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/02/c5/3cb25828105a8b5e4b181cb94d23593f44cfca71c4e1247a6a631dca3dd2/penaltymodel_cache-0.4.1-py3-none-any.whl
Collecting dwave-hybrid==0.5.1 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/cb/aa/0823e6b5ff8433873fab36bbc32bbc0aaf5e3c158601fd018bd1cb484050/dwave_hybrid-0.5.1-py3-none-any.whl
Collecting pyqubo>=0.4.0 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/28/57/ba41de3b13ba23e981463aa1daa2ebe6bd9dcddb15571e4c5905463326c7/pyqubo-0.4.0.tar.gz
Collecting penaltymodel-mip==0.2.3; platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/7d/f5/fa3cc200983692675fdb07c57d6e28ee0b07a98e7ec0955f4d45ab7c4764/penaltymodel_mip-0.2.3-py3-none-any.whl
Collecting penaltymodel==0.16.3 (from dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/e7/1d/d114fe1c401719964fbf404c2c25113edb994df9f93c5773c19da406d192/penaltymodel-0.16.3-py3-none-any.whl
Collecting numpy<2.0.0,>=1.14.0 (from dwave-system==0.9.9->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/69/89/d8fc61a51ded540bd4b8859510b4ae44a0762c8b61dd81eb2c36f5e853ef/numpy-1.19.2-cp38-cp38-win_amd64.whl
Collecting networkx<3.0,>=2.0 (from dwave-system==0.9.9->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl
Collecting homebase<2.0.0,>=1.0.0 (from dwave-system==0.9.9->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/50/ad/e0080c35bd177682d5118a95bc2e7c1ac0541394b4ffce5e9554b6a077f9/homebase-1.0.1-py2.py3-none-any.whl
Collecting six<2.0.0,>=1.11.0 (from dwave-system==0.9.9->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting Flask>=1.1.1 (from dwave-inspector==0.2.3->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting scipy (from minorminer==0.2.0->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/9e/66/57d6cfa52dacd9a57d0289f8b8a614b2b4f9c401c2ac154d6b31ed8257d6/scipy-1.5.2-cp38-cp38-win_amd64.whl
Collecting fasteners (from minorminer==0.2.0->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
Collecting requests[socks]>=2.18 (from dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting click>=7.0 (from dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting plucky>=0.4.3 (from dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/d8/70/7b43e7280284bafecb345f4edb3eea7042cf0d089c5d112920eda650fda5/plucky-0.4.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.7 (from dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting decorator<5.0.0,>=4.1.0 (from dwave-networkx==0.8.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting ortools<8.0.0,>=6.6.4659 (from penaltymodel-mip==0.2.3; platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64"->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/75/53/7d605aad15d2a9d5cbc12362e84d2ccd59ab9deecaed7484f24f656854c4/ortools-7.8.7959-cp38-cp38-win_amd64.whl
Collecting Werkzeug>=0.15 (from Flask>=1.1.1->dwave-inspector==0.2.3->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask>=1.1.1->dwave-inspector==0.2.3->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from Flask>=1.1.1->dwave-inspector==0.2.3->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting monotonic>=0.1 (from fasteners->minorminer==0.2.0->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests[socks]>=2.18->dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests[socks]>=2.18->dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests[socks]>=2.18->dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests[socks]>=2.18->dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting PySocks!=1.5.7,>=1.5.6; extra == "socks" (from requests[socks]>=2.18->dwave-cloud-client==0.7.7->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Collecting protobuf>=3.12.2 (from ortools<8.0.0,>=6.6.4659->penaltymodel-mip==0.2.3; platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64"->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/3b/ba/276d817d4b0184e544a9295e14e95f6148af5c5652033d30eb63d2c13bfa/protobuf-3.13.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->Flask>=1.1.1->dwave-inspector==0.2.3->dwave-ocean-sdk)
  Using cached https://files.pythonhosted.org/packages/4f/8b/da8a2ae5780d38271ac6e691756fc938cf4df8f225eb8aaced0204304932/MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl
Requirement already satisfied: setuptools in c:\users\cambi\ocean\lib\site-packages (from protobuf>=3.12.2->ortools<8.0.0,>=6.6.4659->penaltymodel-mip==0.2.3; platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64"->dwave-ocean-sdk) (41.2.0)
Installing collected packages: numpy, dimod, decorator, networkx, dwave-networkx, scipy, monotonic, six, fasteners, homebase, minorminer, certifi, idna, urllib3, chardet, PySocks, requests, click, plucky, python-dateutil, dwave-cloud-client, dwave-tabu, dwave-system, Werkzeug, itsdangerous, MarkupSafe, Jinja2, Flask, dwave-inspector, dwave-neal, penaltymodel, penaltymodel-lp, penaltymodel-cache, dwavebinarycsp, dwave-qbsolv, dwave-hybrid, pyqubo, protobuf, ortools, penaltymodel-mip, dwave-ocean-sdk
  Running setup.py install for minorminer ... error

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\cambi\ocean\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\cambi\\AppData\\Local\\Temp\\pip-install-1g6f4x5n\\minorminer\\setup.py'"'"'; __file__='"'"'C:\\Users\\cambi\\AppData\\Local\\Temp\\pip-install-1g6f4x5n\\minorminer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\cambi\AppData\Local\Temp\pip-record-3kh8qe14\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cambi\ocean\include\site\python3.8\minorminer'
         cwd: C:\Users\cambi\AppData\Local\Temp\pip-install-1g6f4x5n\minorminer\
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\minorminer
    copying minorminer\minorminer.py -> build\lib.win-amd64-3.8\minorminer
    copying minorminer\package_info.py -> build\lib.win-amd64-3.8\minorminer
    copying minorminer\__init__.py -> build\lib.win-amd64-3.8\minorminer
    creating build\lib.win-amd64-3.8\minorminer\layout
    copying minorminer\layout\layout.py -> build\lib.win-amd64-3.8\minorminer\layout
    copying minorminer\layout\placement.py -> build\lib.win-amd64-3.8\minorminer\layout
    copying minorminer\layout\__init__.py -> build\lib.win-amd64-3.8\minorminer\layout
    running build_ext
    building 'minorminer._minorminer' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\minorminer
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I -I./include/ -I./include/find_embedding -Ic:\users\cambi\ocean\include -IC:\Users\cambi\AppData\Local\Programs\Python\Python38\include -IC:\Users\cambi\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include" /EHsc /Tp./minorminer/_minorminer.cpp /Fobuild\temp.win-amd64-3.8\Release\./minorminer/_minorminer.obj /std:c++latest /MT /EHsc
    clÿ: Ligne de commande warning D9025ÿ: substitution de '/MD' par '/MT'
    _minorminer.cpp
    C:\Users\cambi\AppData\Local\Programs\Python\Python38\include\pyconfig.h(59): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'io.h'ÿ: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\cambi\ocean\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\cambi\\AppData\\Local\\Temp\\pip-install-1g6f4x5n\\minorminer\\setup.py'"'"'; __file__='"'"'C:\\Users\\cambi\\AppData\\Local\\Temp\\pip-install-1g6f4x5n\\minorminer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\cambi\AppData\Local\Temp\pip-record-3kh8qe14\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cambi\ocean\include\site\python3.8\minorminer' Check the logs for full command output.

**Comment by randomir** [comment]
Looks like `minorminer==0.2.0` [does not have wheels built](https://ci.appveyor.com/project/dwave-adtt/minorminer/builds/34288418) for [win/py38](https://pypi.org/project/minorminer/0.2.0/#files).

Please try installing the latest version:
```
pip install minorminer==0.2.3
```

Alternatively, try upgrading to the latest Ocean pre-release:
```
pip install dwave-ocean-sdk==3.0.0.dev0
```
